use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :ham_exam, HamExamWeb.Endpoint,
  on_init: {HamExamWeb.Endpoint, :load_from_system_env, []},
  http: [port: 80, ip: {0, 0, 0, 0}],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: System.get_env("HAM_EXAM_SECRET_KEY_BASE"),
  server: true

# Do not print debug messages in production
config :logger, level: :info
